# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: 이대준 (LEE Daejun)
title: Full Stack & Mobile Developer
email: axa8380@gmail.com
# website: www.github.com/sproogen/resume-theme

# Social links
# twitter_username: facespics
github_username: Soda-Flavour
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
# linkedin_username: jameswgrant
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  4년차 개발자로 다양한 프로덕션 서비스를 개발 한 경험이 있습니다. 새로운 언어와 기술을 쓰는것을 좋아하며, 커뮤니케이션을 중요시하는 개발자입니다.


  결과만 생각하는 난해한 코드보다 모두가 이해할 수 있는 코드을 지향하고 있습니다.
  백앤드 개발의 전문가가 되는것 뿐만 아니라, 서비스의 전반적인 부분을 알고 일하는 개발자가 될 수 있도록 항상 노력하고 있습니다.

  사용기술

  <mark>Node.js</mark> <mark>Javascript</mark> <mark>Flutter</mark> <mark>PHP</mark> <mark>Html</mark> <mark>Css</mark> <mark>Jquery</mark> <mark>Mysql</mark> <mark>Apache</mark> <mark>nginX</mark> <mark>AWS</mark>

# About Section
# about_title: 기술

# Experience Section
# experience_title: Experience

# Projects Section
# projects_title: Projects

# Education Section
# educaton_title: Education

# More Section
# more_title: Military Service
# more_content: | # this will include new lines to allow paragraphs
#   통신장교 중위 전역

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
